### ISSUE TITLE
Migrate merritt ATOM feed code to python3 and deploy serverlessly

### ISSUE THREAD

**Issue by aturner** [ucldc/cdl-nuxeo-code#2]
1) Rewrite for Python 3

2)  Add the additional identifier (ARK?) in the feed

- UCI indicated that not all of the Nuxeo-based "Local Identifiers" are being mapped through to Merritt's "local id" field. Requesting that we update the ATOM feed to include the local identifiers in additional repeated dc:identifier elements.
- Eric L. also noted that UCSF would like to see their local identifiers piped through to Merritt.
- Discussion thread w/ UC3 team: https://cdlib.slack.com/archives/CDT0H72BW/p1662594915311589
- UCI's notes: https://docs.google.com/document/d/1KbI3oaeud7fkf_CkzI0b4SZM7SrqIVtxC7orWuGKHIg/edit
- Nuxeo->Merritt ATOM feed specs: https://docs.google.com/document/d/1s0ijBWu7J2u_D9ZOudvi7a4hZIM1WKqDDdocuuYvEMg/edit#
- We’ll need to coordinate with Eric and Mark on updating Merritt’s code to detect and map through the additional identifiers.

3)  Get it running in Fargate

4) Regenerate ATOM feeds for all sources

5) Run ATOM feeds for newly setup sources. These 32 UCR collections need ATOM feeds:

https://registry.cdlib.org/admin/library_collection/collection/26757/
/asset-library/UCR/SCUA/Archival/WRCA041

https://registry.cdlib.org/admin/library_collection/collection/26758/
/asset-library/UCR/SCUA/Archival/WRCA056

https://registry.cdlib.org/admin/library_collection/collection/26759
/asset-library/UCR/SCUA/Archival/WRCA044

https://registry.cdlib.org/admin/library_collection/collection/27895
/asset-library/UCR/SpecialProjects/wrca_films

https://registry.cdlib.org/admin/library_collection/collection/28126/
/asset-library/UCR/SCUA/Archival/MS002

https://registry.cdlib.org/admin/library_collection/collection/26946
/asset-library/UCR/Test Space/DocNow

https://registry.cdlib.org/admin/library_collection/collection/26761/
/asset-library/UCR/GeneralLibraryCollection/BornDigitalMono

https://registry.cdlib.org/admin/library_collection/collection/27124
/asset-library/UCR/SpecialProjects/SIM

https://registry.cdlib.org/admin/library_collection/collection/28127
/asset-library/UCR/SCUA/Archival/UA310

https://registry.cdlib.org/admin/library_collection/collection/28128
/asset-library/UCR/SCUA/Archival/UA145

https://registry.cdlib.org/admin/library_collection/collection/28129
/asset-library/UCR/SCUA/Archival/UA082

https://registry.cdlib.org/admin/library_collection/collection/28130
/asset-library/UCR/SpecialProjects/WRCA270

https://registry.cdlib.org/admin/library_collection/collection/28131
/asset-library/UCR/SpecialProjects/klc

https://registry.cdlib.org/admin/library_collection/collection/28133
/asset-library/UCR/SCUA/Archival/MS054

https://registry.cdlib.org/admin/library_collection/collection/28134
/asset-library/UCR/SCUA/Archival/MS130

https://registry.cdlib.org/admin/library_collection/collection/28135
/asset-library/UCR/SCUA/Archival/MS233

https://registry.cdlib.org/admin/library_collection/collection/28136
/asset-library/UCR/SCUA/Archival/UA144

https://registry.cdlib.org/admin/library_collection/collection/28137
/asset-library/UCR/SCUA/Archival/MS171

https://registry.cdlib.org/admin/library_collection/collection/28138
/asset-library/UCR/SCUA/Archival/MS071

https://registry.cdlib.org/admin/library_collection/collection/28139
/asset-library/UCR/SCUA/Archival/MS139

https://registry.cdlib.org/admin/library_collection/collection/28140/
/asset-library/UCR/SCUA/Archival/MS170

https://registry.cdlib.org/admin/library_collection/collection/28141
/asset-library/UCR/SCUA/Archival/MS011

https://registry.cdlib.org/admin/library_collection/collection/28142
/asset-library/UCR/SCUA/Archival/MS205

https://registry.cdlib.org/admin/library_collection/collection/28143
/asset-library/UCR/SCUA/Archival/MS032

https://registry.cdlib.org/admin/library_collection/collection/28144
/asset-library/UCR/SCUA/Archival/MS065

https://registry.cdlib.org/admin/library_collection/collection/28145
/asset-library/UCR/SCUA/Archival/MS255

/asset-library/UCR/SCUA/Archival/UA127

**Comment by barbarahui** [comment]
Recreated issue nuxeo-merritt repository: https://github.com/ucldc/nuxeo-merritt/issues/5
